/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import { Scene } from "laya/display/Scene";
import { ClassUtils } from "laya/utils/ClassUtils";
var REG: Function = ClassUtils.regClass;
import { Label } from "laya/ui/Label";
import { RadioGroup } from "laya/ui/RadioGroup";
import { Sprite } from "laya/display/Sprite";
export module ui.test {
    export class TestSceneUI extends Scene {
		public scoreLbl:Label;
		public tipLbll:Label;
		public rd_train:RadioGroup;
        public referenceClass:Array<any>=[Label, RadioGroup, Sprite]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/TestScene");
        }
    }
    REG("ui.test.TestSceneUI",TestSceneUI);
}